version: "3"

services:
  frontend:
    build: 
      context: "./app"
      dockerfile: "./Dockerfile"
    container_name: 'frontend'
    restart: 'always'
    ports:
      - "3000:3000"
  database:
    build:
      context: "./bin/mysql8"
    container_name: "lamp-mysql8"
    restart: "always"
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./config/initdb:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
  phpmyadmin:
    image: phpmyadmin
    container_name: "lamp-phpmyadmin"
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: tiger
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      UPLOAD_LIMIT: 512M
      MEMORY_LIMIT: 512M
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /sessions
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
  redis:
    container_name: "lamp-redis"
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
